#!/usr/bin/env python
from csv import DictReader, DictWriter
from decimal import Decimal
from sys import argv, stdout

fieldnames = (
    "Location",
    "Name",
    "Frequency",
    "Duplex",
    "Offset",
    "Tone",
    "rToneFreq",
    "cToneFreq",
    "DtcsCode",
    "DtcsPolarity",
    "Mode",
    "Comment",
)
#              'TStep', 'Skip', 'Comment', 'URCALL', 'RPT1CALL', 'RPT2CALL')


def drop_decimals(d):
    # Decimal.normalize gives 2E+1 for 20...
    d = str(d)
    if "." in d:
        d = d.rstrip("0").rstrip(".")
    return d


c = open(argv[1], "r")
# Discard the ARRL DATA_SPEC_VERSION line
c.readline()
d = DictReader(c)

w = DictWriter(stdout, fieldnames)
# w.writeheader()
w.writerow(dict(zip(fieldnames, fieldnames)))

i = 0
for row in d:
    in_freq = Decimal(row["INPUT_FREQ"])
    out_freq = Decimal(row["OUTPUT_FREQ"])
    duplex = "off"
    offset = Decimal(0)
    if out_freq < in_freq:
        duplex = "+"
        offset = in_freq - out_freq
    elif out_freq > in_freq:
        duplex = "-"
        offset = out_freq - in_freq
    tone = None
    if row["CTCSS_IN"]:
        tone = "Tone"
    elif row["DCS_CDCSS"]:
        tone = "DTCS"
    mode = None
    if row["FM_WIDE"] == "Y":
        mode = "FM"
    elif row["FM_NARROW"] == "Y":
        mode = "NFM"
    else:
        continue
    if "Y" in (
        row["DSTAR_DV"],
        row["DSTAR_DD"],
        row["DMR"],
        row["FUSION"],
        row["P25_PHASE_1"],
        row["P25_PHASE_2"],
        row["NXDN_DIGITAL"],
        row["ATV"],
        row["DATV"],
    ):
        # These are not Analog modes
        continue
    w.writerow(
        {
            "Location": i,
            "Name": row["CALL"],
            "Frequency": row["OUTPUT_FREQ"],
            "Duplex": duplex,
            "Offset": drop_decimals(offset),
            "Tone": tone,
            "rToneFreq": row["CTCSS_IN"] or "88.5",
            "cToneFreq": row["CTCSS_OUT"] or "88.5",
            "DtcsCode": row["DCS_CDCSS"] or "23",
            "DtcsPolarity": "NN",
            "Mode": mode,
            "Comment": " ".join((row["CALL"], row["CITY"])),
        }
    )
    i += 1

c.close()
