#!/usr/bin/env python3
from wwara.plan import REPEATERS, EXCEPTIONS, ERRORS
from wwara.database import coordinations


def match(channel):
    for rule in REPEATERS:
        if channel in rule:
            return True
    return False


for channel in coordinations(filenames=True):
    if match(channel):
        if not channel.modes:
            print(str(channel) + " ERROR NO MODES")
        else:
            print(channel)
    elif match(~channel):
        print(f"{channel} REVERSED")
    else:
        if channel in EXCEPTIONS:
            print(f"{channel} {EXCEPTIONS[channel]['comment']}")
        elif channel in ERRORS:
            print(f"{channel} ERROR {ERRORS[channel]['comment']}")
        else:
            print(str(channel) + " ERROR!")
