#!/usr/bin/env python
from csv import DictWriter
from decimal import Decimal
from sys import stderr
from wwara.database import coordinations

FIELDNAMES = (
    "Name",
    "Call",
    "Location",
    "Output",
    "Offset",
    "Mode",
    "Latitude",
    "Longitude",
)
LAYERS = {
    "VHF FM": {"low": 144, "high": 148, "mode": "FM"},
    "UHF FM": {"low": 420, "high": 450, "mode": "FM"},
    "VHF DMR": {"low": 144, "high": 148, "mode": "DMR"},
    "UHF DMR": {"low": 420, "high": 450, "mode": "DMR"},
}
CHANNELS = list(coordinations())


def rows(low, high, mode):
    for channel in CHANNELS:
        if (not (low <= channel.input <= high)) or (mode not in channel.modes):
            continue
        yield {
            "Name": str(channel),
            "Call": channel.call,
            "Location": channel.location,
            "Output": channel.output,
            "Offset": channel.offset,
            "Mode": channel.access,
            "Latitude": channel.latitude,
            "Longitude": channel.longitude,
        }


for (
    name,
    layer,
) in LAYERS.items():
    with open(f"{name}.csv", "w", newline="") as csvfile:
        writer = DictWriter(csvfile, fieldnames=FIELDNAMES)
        writer.writeheader()
        writer.writerows(rows(**layer))
