#!/usr/bin/env python
from csv import DictWriter
from decimal import Decimal
from sys import stdout, stderr
from wwara.database import coordinations

FIELDNAMES = (
    "Name",
    "Latitude",
    "Longitude",
)
CHANNELS = list(coordinations())
LAT_LO = 45.90
LAT_HI = 49.00
LON_LO = -124.22
LON_HI = -121.32


def in_region(channel):
    if not (LAT_LO < channel.latitude < LAT_HI):
        return False
    if not (LON_LO < channel.longitude < LON_HI):
        return False
    return True


def rows():
    for channel in CHANNELS:
        if in_region(channel):
            continue
        yield {
            "Name": str(channel),
            "Latitude": channel.latitude,
            "Longitude": channel.longitude,
        }


if __name__ == "__main__":
    writer = DictWriter(stdout, fieldnames=FIELDNAMES)
    writer.writeheader()
    writer.writerows(rows())
