#!/usr/bin/env python3
from channel import Channel
from wwara.database import coordinations
from wwara.plan import REPEATERS

CHANNELS = set()
for rule in REPEATERS:
    output = rule.low
    while output <= rule.high:
        CHANNELS.add(Channel("EMPTY", output, output + rule.offset, bandwidth=rule.bandwidth))
        output += rule.spacing / 1000

for channel in coordinations():
    CHANNELS = {c for c in CHANNELS if not c.overlaps(channel) and not c.overlaps(~channel)}

for channel in sorted(CHANNELS):
    print(channel)
